name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Deploy to ClawCloud via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLAW_HOST }}
          port: 48675
          username: ${{ secrets.CLAW_USERNAME }}
          key: ${{ secrets.CLAW_SSH_KEY }}
          script: |
            docker stop ml-api || true
            docker rm ml-api || true
            rm -rf ~/ml-api
            git clone https://github.com/<your-username>/<your-repo>.git ~/ml-api
            cd ~/ml-api
            docker compose down || true
            docker compose up --build -d