name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}         # e.g., 3.122.123.12
          username: ubuntu                      # or ec2-user for Amazon Linux
          key: ${{ secrets.EC2_SSH_KEY }}       # contents of your .pem file
          port: 22
          script: |
            docker stop ml-api || true
            docker rm ml-api || true
            rm -rf ~/ml-api
            git clone https://github.com/Zad-Walid/Hand-Gesture-Api.git ~/ml-api
            cd ~/ml-api
            docker compose down || true
            docker compose up --build -d
